### ISSUE TITLE
Sass variable button color is missing for material design and iOS in Toast Controller API docs 

### ISSUE THREAD

**Issue by chandanch** [ionic-team/ionic-site#1040]
The button color variable for **closeButtonText** is not documented for iOS and material design but its present for windows platform with the variable name: `$toast-wp-button-color`.  I was able to apply the style for iOS and Material design by using the variables:

**variables.scss**
```sass
// App iOS Variables
// --------------------------------------------------
// iOS only Sass variables can go here
$toast-ios-button-color : #387EF5;
// App Material Design Variables
// --------------------------------------------------
// Material Design only Sass variables can go here
$toast-md-button-color : #387EF5;
```
This adds the color for close button text

[API Doc](http://ionicframework.com/docs/api/components/toast/ToastController/#sass-variables)

**Comment by brandyscarney** [comment]
Thanks for the issue, @chandanch. These variables don't exist in `ionic`. Are you styling the `.toast-button` manually for these modes?

**Comment by chandanch** [comment]
No, I'm not styling manually, I just added:

````sass
$toast-ios-button-color : #387EF5;
$toast-md-button-color : #387EF5;
````
in the `variables.scss` and it applied the color to the toast button. However in Sass variables section of the [API documentiation](http://ionicframework.com/docs/api/components/toast/ToastController/#sass-variables) these variables are not mentioned for iOS and material design, Its available only for windows platform

**Comment by brandyscarney** [comment]
So I figured out what is going on here. Changing the value of [`$toast-wp-button-color`](https://github.com/ionic-team/ionic/blob/master/src/components/toast/toast.wp.scss#L13) actually affects all modes, because it's styling [`.toast-button`](https://github.com/ionic-team/ionic/blob/master/src/components/toast/toast.wp.scss#L78) where it should be styling `.toast-wp .toast-button`. This is actually a bug in the framework, and not a documentation issue, since the `ios` and `md` variables do not exist, and should be added. I created an issue here: https://github.com/ionic-team/ionic/issues/12021
