### ISSUE TITLE
Make Gemfile and Gemfile.lock more flexible

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-site#1203]
Currently, many users must delete the `Gemfile.lock` file and then run `bundle exec bundle install` and then locally ignore `Germfile.lock`. It appears the lock file restricts what version of Ruby is installed. Heroku needs a Ruby version specified in the Gemfile, but the lock should be compatible with other versions.

**Comment by goodells** [comment]
My understanding of this is that the `Gemfile` contains the project's direct dependencies as we've specified them, and the `Gemfile.lock` contains a snapshot of the Ruby version and further dependencies.  That's why even though we only need Jekyll and kramdown, there are a bunch of gems listed in the lockfile.  This can cause issues because the set of dependencies that work (listed in the lockfile) will vary depending on the user's platform, Ruby version, and sign of the Zodiac.

If we want the `Gemfile.lock` in version control, it's not really possible to avoid the fact that it won't work for some people.  If Heroku needs it, we could add a `bundle install` invocation in the CI, but that will add some time to the process.

**Comment by perrygovier** [comment]
the lockfile might not be necessary. wanna play with it? 
https://devcenter.heroku.com/articles/ruby-versions
You should now have access to the dev server in Heroku

**Comment by goodells** [comment]
It looks like Heroku is becoming more flexible with how it accepts Ruby deployment, but I think it is quite insistent on having `Gemfile.lock`.  This lays out some of the challenges involved in re-constructing it, and how to mitigate issues when working with developers on different platforms (the issue we are facing):

https://devcenter.heroku.com/articles/bundler-windows-gemfile#bundle-install-with-no-lockfile

One solution for this is to automate the removal and re-installation of the lockfile for local development with a simple script in `package.json` like `npm run install` (-> `rm Gemfile.lock && bundle exec bundle install`).
