### ISSUE TITLE
Docs wrong for ionSwipe event on expandable ItemSliding

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1213]
_From @jwt02180 on July 25, 2017 16:29_

**Ionic version:**  (check one with "x")
[ ] **1.x** (For Ionic 1.x issues, please use https://github.com/ionic-team/ionic-v1)
[ ] **2.x**
[ X ] **3.x**

**I'm submitting a ...**  (check one with "x")
[ X ] documentation error
[ ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or http://ionicworldwide.herokuapp.com/

**Current behavior:**
I've been trying to add the full-swipe action to a sliding item in a list. When placed on the `<ion-item-sliding>` element as per the [ItemSliding Docs](http://ionicframework.com/docs/api/components/item/ItemSliding/#usage) the ionSwipe event didn't seem to fire properly for me.

The [ItemOptions Docs](http://ionicframework.com/docs/api/components/item/ItemOptions/#usage) **are** correct

**Expected behavior:**
The ionSwipe event should fire when a full swipe occurs on an a list item.

**Other information:**
The documentation says to place the event listener on the `<ion-item-sliding>` element, but the source code fires the event on the `<ion-item-options>` element. This makes sense so you can have the ionSwipe event be set for options on each sliding direction of an item.

_**I'm just asking that the docs get updated to reflect this.**_

_Copied from original issue: ionic-team/ionic#12467_

**Comment by Jamie-Vangeysel** [comment]
I almost can't believe this is still an issue seriously ...

**Comment by brandyscarney** [comment]
The API documentation reflects the documentation at the time of the latest stable release (for 3.x that is 3.9.2). The documentation for this was updated, but because we haven't released a new version of 3.x because of our work on 4.x, the documentation will continue to reflect the old usage of the 3.9.2 release.

The commit to update the documentation was made on March 9, 2018 (https://github.com/ionic-team/ionic/commit/aad67ab299f5810a37ce56e16e8bd69700bbc158) but the release for 3.9.2 was November 8, 2017 (https://github.com/ionic-team/ionic/releases/tag/v3.9.2) so this documentation update did not make it in to the last release. 

**If you want to see the latest documentation that is in master for any component** switch to the nightly dropdown as that is updated frequently:

<img width="228" alt="screen shot 2019-01-14 at 3 08 06 pm" src="https://user-images.githubusercontent.com/6577830/51138094-389e0680-180e-11e9-83c3-155568312e7d.png">

This will reflect the latest state of the 3.x documentation: https://ionicframework.com/docs/nightly/api/components/item/ItemSliding/#expandable-options

With all of that said, I believe we need to look into the doc generation process to make sure it is properly working still since there hasn't been an update to the nightly documentation since March for v3. I believe it has to do with us moving the v3 source: https://github.com/ionic-team/ionic-v3/

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
