### ISSUE TITLE
Make demo app visible on mobile and smaller resolutions

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-site#1219]
If you view the docs with a mobile device right now you seem to have no way to actually look at the demo that is included in the docs page.

**Comment by janpio** [comment]
(Seems to even be a general breakpoint @ 1100px, not limited to mobile)

Solution could be to be able to click/tap a button that opens a "modal" with the demo page that then can be closed again.

**Comment by goodells** [comment]
Thanks for noticing and reporting this.

We discussed this earlier when making some changes to the documentation and have actually added mobile-viewable links to the demos on the [components page](http://ionicframework.com/docs/components/).  These links become visible above the demo source code blocks on mobile screen sizes.

It is our intention to add similar links to the API documentation in the future, but that process is more involved because those pages are generated automatically from annotations in the Ionic Source.
