### ISSUE TITLE
docs: CLI documentation is broken

### ISSUE THREAD

**Issue by jgw96** [ionic-team/ionic-site#1230]
_From @Polyergic on August 8, 2017 20:15_

**Type**: <span ionic-type>docs</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>all</span>  

<span ionic-description>https://ionicframework.com/docs/cli/build kicks me back to https://ionicframework.com/docs/cli/.  There doesn't seem to be a way to access the documentation for `build`</span>

<span is-issue-template></span>

_Copied from original issue: ionic-team/ionic#12620_

**Comment by goodells** [comment]
This was done here:  https://github.com/ionic-team/ionic-site/commit/1296317280b2219c47bd72f89581f1a3b07fe949

I can't find the issue for it and there might not have been one, but this was intentional at the time.  Should we change it?

**Comment by Polyergic** [comment]
If the goal was to make `build` undocumented, you could remove the link - no link would be less confusing than a link that just sends you back to where you just followed the link from.  Since the removed documentation says "The build command is a proxy for Cordova's [build command](https://cordova.apache.org/docs/en/latest/guide/cli/index.html#link-5)", the short description in the command list could include the link to Cordova.

I ran in to this while trying to figure out what the difference is between `ionic build` and `ionic-app-scripts build` (specifically, why the former complains about a lack of platforms and the latter is happy to just build a web version).  Looking up the documentation for `ionic build` seemed like the obvious place to start.

**Comment by janpio** [comment]
>  but this was intentional at the time. Should we change it?

With CLI 3.x the old `ionic build` command was renamed to `ionic cordova build`.
CLI 3.6 then added new functionality as `ioinc build` again.

So yes, this should be changed. There should be a new documentation available from Ionic CLI.

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
