### ISSUE TITLE
/formulas/localstorage page is redirected (2)

### ISSUE THREAD

**Issue by notslang** [ionic-team/ionic-site#1389]
This is a continuation of #1388 (because that issue was locked) and a reply to this comment by @mhartington:

> Sorry, typo in my comment. The redirects are working fine, though a bit odd. Either way, the articles content can be found here:
> https://github.com/ionic-team/ionic-learn/blob/master/content/formulas/localstorage/article.md

The fact that the redirect is working _is_ the issue that I'm reporting. All the links to content on that site are effectively broken because that redirect happens. Either the redirect needs to be removed, or someone needs to go find all the places where people have linked to learn.ionicframework.com and update those to point to an archived version (or the GitHub repo).

Obviously removing that redirect is a better solution than trying to edit every related Stack Overflow post and contact everyone who has linked to it on their own websites.

It looks like the redirect is being caused by this meta tag at the top of every page:

```html
<meta http-equiv="refresh" content="0; url=http://ionicframework.com/getting-started">
```

I would submit a PR to fix it myself, but the GitHub repo for learn.ionicframework.com was archived.

**Comment by jcesarmobile** [comment]
I'm sorry for the inconvenience, but at this point the redirect is from the hostname and we can't do what you requested.
But even when you requested it, it was not a feasible action as the project was deprecated and would have required to keep it running forever so it could do the redirects.
We are not responsible for people linking us, and StackOverflow policy is to include the relevant information on the answer, so if the link stops working you still get the info, because links stop working over time.
