### ISSUE TITLE
Roadmap built off of github API

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-site#425]

**Comment by jgw96** [comment]
@perrygovier this might be helpful? https://github.com/indexzero/roadmap

**Comment by perrygovier** [comment]
@andrewmcgivery put together something like this a while back that gets us most of the way there. Lets see if we can get his OK to build it based on that and give him credit. 
http://ionic.mcgivery.com/roadmap/#

**Comment by andrewmcgivery** [comment]
Katie and I were actually discussing this very topic not that long ago (February or March). :)

You are more than welcome to take as much as you need from my prototype. I built the prototype with JQuery since it was a quick afternoon project, but it shouldn't be too hard to change it to whatever is desired.

Let me know if you need any assistance or have any questions! More than happy to help where I can.

**Comment by perrygovier** [comment]
@bensperry, do you want to design this or should we just build and then tweak?

**Comment by bensperry** [comment]
I'll let you guys handle it, and offer feedback along the way!

**Comment by brandyscarney** [comment]
It would be cool if switching between version 1 & 2 was a different URL so we could link people to it. :smile:

**Comment by danielsogl** [comment]
@brandyscarney this can be closed I think
