### ISSUE TITLE
Duplicate ionic sass variables

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-site#846]
See screenshot below. It appears there are duplicate styles on [this](http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/) page. If they aren't duplicates, the same name is extremely confusing. 

![image](https://cloud.githubusercontent.com/assets/2852839/19496814/8ab1c704-9589-11e6-8889-bd4a3f9d49b1.png)

**Comment by brandyscarney** [comment]
It's because it's pulling in variables from each theme file, the default one:

https://github.com/driftyco/ionic/blob/master/src/themes/ionic.theme.default.scss

and the dark theme:

https://github.com/driftyco/ionic/blob/master/src/themes/ionic.theme.dark.scss

We need to clean this up, just not sure how we should handle it. cc @briandennis @perrygovier

**Comment by perrygovier** [comment]
Pruning legacy docs issues. If you'd still like these fixed, please open a PR on @ionic-team/ionic-legacy-docs
